version: "3.4"
services:
  deluge:
    container_name: deluge
    image: linuxserver/deluge:latest
    restart: unless-stopped
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - ${DOWNLOAD_ROOT}/downloads:/downloads # downloads folder
      - ${CONFIG_ROOT}/deluge:/config # config files
    ports:
      - 8112:8112

  jackett:
    container_name: jackett
    image: linuxserver/jackett:latest
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOWNLOAD_ROOT}/downloads/torrent-blackhole:/downloads # place where to put .torrent files for manual download
      - ${CONFIG_ROOT}/jackett:/config # config files
    ports:
      - 9117:9117

  nzbget:
    container_name: nzbget
    image: linuxserver/nzbget:latest
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - ${DOWNLOAD_ROOT}/downloads:/downloads # download folder
      - ${CONFIG_ROOT}/nzbget:/config # config files
    ports:
      - 6789:6789

  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr:latest
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIG_ROOT}/sonarr:/config # config files
      - ${DOWNLOAD_ROOT}/complete/tv:/tv # tv shows folder
      - ${DOWNLOAD_ROOT}/downloads:/downloads # download folder
    ports:
      - 8989:8989

  lidarr:
    container_name: lidarr
    image: linuxserver/lidarr:latest
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIG_ROOT}/lidarr:/config # config files
      - ${DOWNLOAD_ROOT}/complete/music:/music # tv shows folder
      - ${DOWNLOAD_ROOT}/downloads:/downloads # download folder
    ports:
      - 8686:8686

  radarr:
    container_name: radarr
    image: linuxserver/radarr:latest
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIG_ROOT}/radarr:/config # config files
      - ${DOWNLOAD_ROOT}/complete/movies:/movies # movies folder
      - ${DOWNLOAD_ROOT}/downloads:/downloads # download folder
    ports:
      - 7878:7878

  plex-server:
    container_name: plex-server
    image: plexinc/pms-docker:latest
    restart: unless-stopped
    environment:
      - TZ=${TZ} # timezone, defined in .env
    network_mode: host
    volumes:
      - ${CONFIG_ROOT}/plex/db:/config # plex database
      - ${CONFIG_ROOT}/plex/transcode:/transcode # temp transcoded files
      - ${DOWNLOAD_ROOT}/complete:/data # media library
    ports:
      - 32400:32400

  bazarr:
    container_name: bazarr
    image: linuxserver/bazarr
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
      - UMASK_SET=022 #optional
    volumes:
      - ${CONFIG_ROOT}/bazarr:/config # config files
      - ${DOWNLOAD_ROOT}/complete/movies:/movies # movies folder
      - ${DOWNLOAD_ROOT}/complete/tv:/tv # tv shows folder
    ports:
      - 6767:6767

  portainer:
    container_name: portainer
    image: portainer/portainer-ce
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    ports:
      - 9000:9000

  samba:
    container_name: samba
    image: dperson/samba
    environment:
      - TZ=${TZ}
    network_mode: host
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    read_only: true
    tmpfs:
      - /tmp
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - ${DOWNLOAD_ROOT}/complete:/mnt:z
      - /home/${SAMBA_USERNAME}:/${SAMBA_USERNAME}:z
    command: '-s "${SAMBA_SHARE_COMPLETE};/mnt;yes;no;no;${SAMBA_USERNAME}" -s "${SAMBA_SHARE_HOME};/${SAMBA_USERNAME};yes;no;no;${SAMBA_USERNAME}" -u "${SAMBA_USERNAME};${SAMBA_PASSWORD}" -p'

  adguardhome:
    container_name: adguardhome
    image: adguard/adguardhome:latest
    network_mode: host
    restart: unless-stopped
    volumes:
      - ${CONFIG_ROOT}/adguardhome/work:/opt/adguardhome/work # config files
      - ${CONFIG_ROOT}/adguardhome/conf:/opt/adguardhome/conf # config files

  homeassistant:
    container_name: home-assistant
    image: homeassistant/home-assistant:stable
    environment:
      - TZ=${TZ}
    volumes:
      - ${CONFIG_ROOT}/homeassistant:/config
    restart: unless-stopped
    network_mode: host

volumes:
  portainer_data:
